/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:05:57 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/Now Playing Module.bundle/Now Playing Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSystemMenuUI/TVSMActionModule.h>

@protocol NSCopying;
@class TVSMButtonViewController, TVNPEndpointRouteConnection;

@interface TVSMNowPlayingModule : TVSMActionModule {

	TVSMButtonViewController* _buttonViewController;
	TVNPEndpointRouteConnection* _routeConnection;
	id<NSCopying> _metadataObserverToken;

}

@property (nonatomic,readonly) TVSMButtonViewController * buttonViewController;              //@synthesize buttonViewController=_buttonViewController - In the implementation block
@property (nonatomic,readonly) TVNPEndpointRouteConnection * routeConnection;                //@synthesize routeConnection=_routeConnection - In the implementation block
@property (nonatomic,readonly) id<NSCopying> metadataObserverToken;                          //@synthesize metadataObserverToken=_metadataObserverToken - In the implementation block
+(long long)buttonStyle;
-(TVSMButtonViewController *)buttonViewController;
-(id<NSCopying>)metadataObserverToken;
-(void)_updateButtonViewController;
-(id)init;
-(void)dealloc;
-(id)contentViewController;
-(void)handleAction;
-(BOOL)dismissAfterAction;
-(TVNPEndpointRouteConnection *)routeConnection;
@end

