/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:04:05 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/Audio Routing Module.bundle/Audio Routing Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Audio Routing Module/Audio Routing Module-Structs.h>
#import <UIKitCore/UICollectionViewLayoutAttributes.h>

@interface TVNPRoutingRoutesCollectionViewLayoutAttributes : UICollectionViewLayoutAttributes {

	BOOL _showingVolumeSlider;
	BOOL _enabled;

}

@property (assign,getter=isShowingVolumeSlider,nonatomic) BOOL showingVolumeSlider;              //@synthesize showingVolumeSlider=_showingVolumeSlider - In the implementation block
@property (assign,getter=isEnabled,nonatomic) BOOL enabled;                                      //@synthesize enabled=_enabled - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)init;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isEnabled;
-(void)setShowingVolumeSlider:(BOOL)arg1 ;
-(BOOL)isShowingVolumeSlider;
@end

