/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:04:05 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/Audio Routing Module.bundle/Audio Routing Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Audio Routing Module/TVNPRoutingDestination.h>
#import <libobjc.A.dylib/MPVolumeControllerDelegate.h>

@protocol NSCopying;
@class MPAVEndpointRoute, TVNPEndpointRouteConnection, MPVolumeController, NSString;

@interface TVNPEndpointRoutingDestination : TVNPRoutingDestination <MPVolumeControllerDelegate> {

	MPAVEndpointRoute* _endpointRoute;
	TVNPEndpointRouteConnection* _routeConnection;
	MPVolumeController* _volumeController;
	id<NSCopying> _routeConnectionObserverToken;
	unsigned long long _connectionState;

}

@property (nonatomic,readonly) TVNPEndpointRouteConnection * routeConnection;              //@synthesize routeConnection=_routeConnection - In the implementation block
@property (nonatomic,readonly) MPVolumeController * volumeController;                      //@synthesize volumeController=_volumeController - In the implementation block
@property (nonatomic,readonly) id<NSCopying> routeConnectionObserverToken;                 //@synthesize routeConnectionObserverToken=_routeConnectionObserverToken - In the implementation block
@property (assign,nonatomic) unsigned long long connectionState;                           //@synthesize connectionState=_connectionState - In the implementation block
@property (assign,nonatomic) BOOL isCurrentDestination; 
@property (nonatomic,readonly) MPAVEndpointRoute * endpointRoute;                          //@synthesize endpointRoute=_endpointRoute - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)_playbackStateForMPCPlaybackState:(long long)arg1 ;
+(id)keyPathsForValuesAffectingConnected;
+(id)keyPathsForValuesAffectingDisconnected;
+(id)keyPathsForValuesAffectingPaired;
-(NSString *)description;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(BOOL)isConnected;
-(unsigned long long)connectionState;
-(BOOL)isPaired;
-(void)setConnectionState:(unsigned long long)arg1 ;
-(void)setVolumeLevel:(id)arg1 ;
-(void)volumeController:(id)arg1 volumeControlAvailableDidChange:(BOOL)arg2 ;
-(void)volumeController:(id)arg1 volumeValueDidChange:(float)arg2 ;
-(MPVolumeController *)volumeController;
-(MPAVEndpointRoute *)endpointRoute;
-(BOOL)isDisconnected;
-(void)togglePlayPause;
-(id)initWithEndpointRoute:(id)arg1 ;
-(TVNPEndpointRouteConnection *)routeConnection;
-(void)_metadataDidChange:(id)arg1 forKeys:(id)arg2 ;
-(void)refreshPropertiesWithRoute:(id)arg1 ;
-(void)_updateVolume;
-(void)connectAndPair;
-(void)setIsCurrentDestination:(BOOL)arg1 ;
-(id<NSCopying>)routeConnectionObserverToken;
@end

