/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:04:05 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/Audio Routing Module.bundle/Audio Routing Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSIndexSet;

@interface TVNPArrayChange : NSObject {

	long long _changeType;
	NSIndexSet* _sourceIndexes;
	NSIndexSet* _destinationIndexes;

}

@property (nonatomic,readonly) long long changeType;                              //@synthesize changeType=_changeType - In the implementation block
@property (nonatomic,copy,readonly) NSIndexSet * sourceIndexes;                   //@synthesize sourceIndexes=_sourceIndexes - In the implementation block
@property (nonatomic,copy,readonly) NSIndexSet * destinationIndexes;              //@synthesize destinationIndexes=_destinationIndexes - In the implementation block
+(id)arrayChangeInsert:(id)arg1 ;
+(id)arrayChangeDelete:(id)arg1 ;
+(id)arrayChangeMove:(unsigned long long)arg1 toIndex:(unsigned long long)arg2 ;
-(id)description;
-(long long)changeType;
-(NSIndexSet *)sourceIndexes;
-(NSIndexSet *)destinationIndexes;
@end

