/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:06:12 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/People Picker Module.bundle/People Picker Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, TVPeoplePickerUser, TVPeoplePickerCache, TVPeoplePickerProfilePhotoStore;

@interface TVPeoplePickerDataSource : NSObject {

	NSArray* _users;
	TVPeoplePickerUser* _currentUser;
	long long _currentUserIndex;
	TVPeoplePickerCache* _cache;
	TVPeoplePickerProfilePhotoStore* _profilePhotoStore;

}

@property (assign,nonatomic) long long currentUserIndex;                                       //@synthesize currentUserIndex=_currentUserIndex - In the implementation block
@property (nonatomic,retain) TVPeoplePickerCache * cache;                                      //@synthesize cache=_cache - In the implementation block
@property (nonatomic,retain) TVPeoplePickerProfilePhotoStore * profilePhotoStore;              //@synthesize profilePhotoStore=_profilePhotoStore - In the implementation block
@property (nonatomic,copy,readonly) NSArray * users;                                           //@synthesize users=_users - In the implementation block
@property (nonatomic,retain) TVPeoplePickerUser * currentUser;                                 //@synthesize currentUser=_currentUser - In the implementation block
-(void)_fetchProfilePhotosForAllUsers;
-(void)_fetchUsers:(BOOL)arg1 ;
-(void)setProfilePhotoStore:(TVPeoplePickerProfilePhotoStore *)arg1 ;
-(long long)currentUserIndex;
-(void)setCurrentUserIndex:(long long)arg1 ;
-(TVPeoplePickerProfilePhotoStore *)profilePhotoStore;
-(id)init;
-(TVPeoplePickerCache *)cache;
-(TVPeoplePickerUser *)currentUser;
-(void)setCurrentUser:(TVPeoplePickerUser *)arg1 ;
-(void)setCache:(TVPeoplePickerCache *)arg1 ;
-(NSArray *)users;
@end

