/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:06:12 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/People Picker Module.bundle/People Picker Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/TVSMModuleContentViewControllerDelegate.h>
#import <libobjc.A.dylib/TVSMModule.h>

@protocol TVSMModuleContentViewController, TVSMModuleDelegate;
@class NSArray, TVSMMonogramViewController, NSObservation, TVPeoplePickerUser, NSString;

@interface TVSMPeoplePickerPersonModule : NSObject <TVSMModuleContentViewControllerDelegate, TVSMModule> {

	TVSMMonogramViewController*<TVSMModuleContentViewController> _contentViewController;
	NSObservation* _profilePhotoObserver;
	BOOL _selected;
	id<TVSMModuleDelegate> _delegate;
	long long _type;
	TVPeoplePickerUser* _user;
	/*^block*/id _actionHandler;

}

@property (nonatomic,readonly) TVPeoplePickerUser * user;                                                                             //@synthesize user=_user - In the implementation block
@property (nonatomic,copy) id actionHandler;                                                                                          //@synthesize actionHandler=_actionHandler - In the implementation block
@property (assign,nonatomic) BOOL selected;                                                                                           //@synthesize selected=_selected - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<TVSMModuleDelegate> delegate;                                                                  //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) long long type;                                                                                        //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) UIViewController*<TVSMModuleContentViewController> contentViewController; 
@property (nonatomic,readonly) UIViewController*<TVSMModuleExpandedContentViewController> expandedContentViewController; 
@property (nonatomic,readonly) NSArray * childModules; 
+(long long)buttonStyle;
-(void)_updateContentViewControllerForUser:(id)arg1 ;
-(TVPeoplePickerUser *)user;
-(long long)type;
-(id<TVSMModuleDelegate>)delegate;
-(void)setDelegate:(id<TVSMModuleDelegate>)arg1 ;
-(id)initWithUser:(id)arg1 ;
-(void)setSelected:(BOOL)arg1 ;
-(BOOL)selected;
-(id)actionHandler;
-(void)setActionHandler:(id)arg1 ;
-(UIViewController*<TVSMModuleContentViewController>)contentViewController;
-(void)handleAction;
-(BOOL)dismissAfterAction;
-(void)contentModuleViewControllerDidTriggerAction:(id)arg1 ;
@end

