/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:06:12 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/People Picker Module.bundle/People Picker Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSystemMenuUI/TVSMCollectionModule.h>

@protocol TVSMModuleContentViewController;
@class TVSMMonogramViewController, TVPeoplePickerDataSource, NSArray;

@interface TVSMPeoplePickerModule : TVSMCollectionModule {

	TVSMMonogramViewController*<TVSMModuleContentViewController> _contentViewController;
	TVPeoplePickerDataSource* _dataSource;
	NSArray* _childModules;

}
+(long long)buttonStyle;
-(void)_updateContentViewControllerForModule:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(id)childModules;
@end

