/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:06:12 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/People Picker Module.bundle/People Picker Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <People Picker Module/People Picker Module-Structs.h>
@class NSOperationQueue;

@interface TVPeoplePickerProfilePhotoStore : NSObject {

	double _monogramDiameter;
	NSOperationQueue* _networkQueue;

}

@property (nonatomic,retain) NSOperationQueue * networkQueue;              //@synthesize networkQueue=_networkQueue - In the implementation block
@property (assign,nonatomic) double monogramDiameter;                      //@synthesize monogramDiameter=_monogramDiameter - In the implementation block
-(void)_fetchPhotoRequest:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)_croppedImageWithRect:(CGRect)arg1 originalImage:(id)arg2 ;
-(id)initWithMonogramDiameter:(double)arg1 ;
-(void)fetchPhotoForPrimaryAccount:(/*^block*/id)arg1 ;
-(void)fetchPhotoForDSID:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)cancelAllPendingOperations;
-(void)setNetworkQueue:(NSOperationQueue *)arg1 ;
-(double)monogramDiameter;
-(void)setMonogramDiameter:(double)arg1 ;
-(NSOperationQueue *)networkQueue;
@end

