/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:06:12 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/People Picker Module.bundle/People Picker Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSCache;

@interface TVPeoplePickerCache : NSObject {

	NSCache* _memoryCache;

}

@property (nonatomic,retain) NSCache * memoryCache;              //@synthesize memoryCache=_memoryCache - In the implementation block
-(id)profilePhotoForDSID:(id)arg1 ;
-(void)setProfilePhotoData:(id)arg1 forDSID:(id)arg2 ;
-(id)_cacheFileForDSID:(id)arg1 ;
-(id)_cacheDirectoryURL;
-(void)setMemoryCache:(NSCache *)arg1 ;
-(id)init;
-(NSCache *)memoryCache;
@end

