/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:06:12 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/People Picker Module.bundle/People Picker Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class TVSUser, NSNumber, NSString, UIImage;

@interface TVPeoplePickerUser : NSObject {

	TVSUser* _user;
	NSNumber* _DSID;
	NSString* _firstName;
	NSString* _lastName;
	UIImage* _profilePhoto;

}

@property (nonatomic,readonly) TVSUser * user;                    //@synthesize user=_user - In the implementation block
@property (nonatomic,readonly) NSNumber * DSID;                   //@synthesize DSID=_DSID - In the implementation block
@property (nonatomic,readonly) NSString * firstName;              //@synthesize firstName=_firstName - In the implementation block
@property (nonatomic,readonly) NSString * lastName;               //@synthesize lastName=_lastName - In the implementation block
@property (nonatomic,retain) UIImage * profilePhoto;              //@synthesize profilePhoto=_profilePhoto - In the implementation block
-(void)setProfilePhoto:(UIImage *)arg1 ;
-(UIImage *)profilePhoto;
-(TVSUser *)user;
-(id)initWithUser:(id)arg1 ;
-(NSString *)firstName;
-(NSString *)lastName;
-(NSNumber *)DSID;
@end

