/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:04:05 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/Audio Routing Module.bundle/Audio Routing Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSystemMenuUI/TVSMExpandingModule.h>

@class TVNPGroupableRoutingController;

@interface TVNPAirPlayRoutingModule : TVSMExpandingModule {

	TVNPGroupableRoutingController* _routingController;

}

@property (nonatomic,readonly) TVNPGroupableRoutingController * routingController;              //@synthesize routingController=_routingController - In the implementation block
+(long long)buttonStyle;
-(id)init;
-(TVNPGroupableRoutingController *)routingController;
-(id)expandedContentViewController;
@end

