/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:04:05 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/Audio Routing Module.bundle/Audio Routing Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Audio Routing Module/TVNPBaseRoutingDestinationCollectionViewCell.h>

@class TVNPRoutingDestination;

@interface TVNPRoutingDestinationCollectionViewCell : TVNPBaseRoutingDestinationCollectionViewCell {

	TVNPRoutingDestination* _destination;

}

@property (nonatomic,retain) TVNPRoutingDestination * destination;              //@synthesize destination=_destination - In the implementation block
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setDestination:(TVNPRoutingDestination *)arg1 ;
-(TVNPRoutingDestination *)destination;
-(void)_updateNowPlayingInfo;
-(void)_updateMusicBarState;
@end

