/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 10, 2019 at 4:04:05 AM Mountain Standard Time
* Operating System: Version 13.2 (Build 17K82)
* Image Source: /System/Library/TVSystemMenuModules/Audio Routing Module.bundle/Audio Routing Module
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Audio Routing Module/Audio Routing Module-Structs.h>
#import <UIKitCore/UIView.h>

@interface TVNPNowPlayingProgressView : UIView {

	float _progress;

}

@property (getter=_progressCenter,nonatomic,readonly) CGPoint progressCenter; 
@property (assign,nonatomic) float progress;                                               //@synthesize progress=_progress - In the implementation block
-(float)progress;
-(void)setProgress:(float)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setProgress:(float)arg1 animated:(BOOL)arg2 ;
-(void)tintColorDidChange;
-(CGPoint)_progressCenter;
-(CGSize)_fillSize;
@end

